ARDMK_DIR=../lib/arduino
BOARD_TAG=attiny85 
MCU=attiny85
ARDUINO_QUIET=1
ARDUINO_VAR_PATH=../lib/tiny/avr/cores/tiny/
ARDUINO_CORE_PATH=../lib/tiny/avr/cores/tiny/
AVR_TOOLS_DIR=/usr
TARGET=ledtest
OBJDIR=bin/
F_CPU=8000000L

include $(ARDMK_DIR)/Arduino.mk
